// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static  FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCGS_53NDug3QlRAp7fJeMdIU7zbfgBvDA',
//     appId: '1:769140719411:web:18c277b88fd3deaa258846',
//     messagingSenderId: '769140719411',
//     projectId: 'my-project-39ad7',
//     authDomain: 'my-project-39ad7.firebaseapp.com',
//     storageBucket: 'my-project-39ad7.appspot.com',
//     measurementId: 'G-88L4P95TSV',
//   );
//
//   static  FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBSdrplnigrd3feeR4aWh7kZS1yFuc7quc',
//     appId: '1:769140719411:android:4a7e2ed599a22dec258846',
//     messagingSenderId: '769140719411',
//     projectId: 'my-project-39ad7',
//     storageBucket: 'my-project-39ad7.appspot.com',
//   );
//
//   static FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBqZxSP9Eql7v4nl4BIGqk2BZEKZq0k2b0',
//     appId: '1:769140719411:ios:6c4cb583e9976c6b258846',
//     messagingSenderId: '769140719411',
//     projectId: 'my-project-39ad7',
//     storageBucket: 'my-project-39ad7.appspot.com',
//     iosBundleId: 'com.example.myProject',
//   );
//
//   static  FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBqZxSP9Eql7v4nl4BIGqk2BZEKZq0k2b0',
//     appId: '1:769140719411:ios:6c4cb583e9976c6b258846',
//     messagingSenderId: '769140719411',
//     projectId: 'my-project-39ad7',
//     storageBucket: 'my-project-39ad7.appspot.com',
//     iosBundleId: 'com.example.myProject',
//   );
//
//   static  FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCGS_53NDug3QlRAp7fJeMdIU7zbfgBvDA',
//     appId: '1:769140719411:web:b29a613f4d871c14258846',
//     messagingSenderId: '769140719411',
//     projectId: 'my-project-39ad7',
//     authDomain: 'my-project-39ad7.firebaseapp.com',
//     storageBucket: 'my-project-39ad7.appspot.com',
//     measurementId: 'G-JG6TQ5SHDV',
//   );
// }
